services:
  redis-server:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: redis-server
    restart: unless-stopped
    ports:
      - "127.0.0.1:6379:6379"
    volumes:
      - ../redis-data:/var/lib/redis
      - ./redis.conf:/usr/local/etc/redis/redis.conf
    environment:
      - TZ=Europe/Istanbul
    networks:
      - redis-network
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 30s
    deploy:
      resources:
        limits:
          cpus: "1"
          memory: 1G
        reservations:
          cpus: "0.5"
          memory: 512M

networks:
  redis-network:
    driver: bridge
